<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Clients\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Clients\WeatherClient\WeatherClient.csproj" />
    <ProjectReference Include="Clients\ParksRpcClient\ParksRpcClient.csproj" />
    <ProjectReference Include="Clients\AstroClient\AstroClient.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
